# Étape base
FROM node:20-alpine AS base
WORKDIR /app/backend
COPY backend/package*.json .
RUN npm install

# Étape dev
FROM base AS dev
CMD ["sh", "-c", "npx prisma db push && npm run start:dev"]

# Étape build
FROM base AS build
WORKDIR /app
COPY shared shared
COPY backend/ backend
WORKDIR /app/backend
RUN npx prisma generate 
RUN npm run build

# Étape prod
FROM node:20-alpine AS prod
WORKDIR /app/backend
COPY --from=build /app/backend/dist ./dist
COPY backend/prisma ./prisma
COPY backend/package*.json ./   
RUN npm ci --only=production
COPY --from=build /app/backend/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/backend/node_modules/@prisma ./node_modules/@prisma
CMD ["node", "dist/main"]
