name: app-dev
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      target: dev
    volumes:
      - ../backend:/app/backend
      - ../shared:/app/shared
      - /app/backend/node_modules
    ports:
      - '5001:3000'
    depends_on:
      - postgres
      - ocr
    # environment:
    #   - NODE_ENV=development
    # - DATABASE_URL=postgresql://postgres:postgres@postgres:5433/db
    environment:
      OCR_BASE_URL: http://ocr:8000
    env_file:
      - ../backend/.env.development

  ocr:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ocr
      target: prod
    restart: always
    expose:
      - '8000'

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      target: dev
    volumes:
      - ../frontend:/app/frontend
      - ../shared:/app/shared
      - /app/frontend/node_modules
    ports:
      - '8080:8080'
    command: npm run dev
volumes:
  postgres_data:
