# Étape de base commune
FROM node:24.18.0-bookworm-slim AS base
WORKDIR /app/frontend
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
#RUN mkdir frontend
COPY frontend/package*.json ./
RUN npm ci

# Étape de développement (hot reload)
FROM base AS dev
CMD ["npm", "run", "dev"]

# Étape de build (compilation en HTML/JS/CSS)
FROM base AS build
WORKDIR /app
COPY shared/ shared
COPY backend backend
COPY frontend/ frontend
WORKDIR /app/backend
RUN npm ci
RUN if [ -f .env.production ]; then \
        NODE_ENV=production npx prisma generate --generator shared; \
    else \
        npx prisma generate --generator shared; \
    fi
WORKDIR /app/frontend
RUN npm run build

# Production Step (caddy TLS + reverse proxy)
FROM caddy:2-alpine AS prod
COPY docker/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/frontend/dist /usr/share/caddy

# Étape de production (serveur nginx)
# FROM nginx:alpine AS prod
# COPY --from=build /app/frontend/dist /usr/share/nginx/html
# COPY docker/nginx.conf /etc/nginx/nginx.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
