# Étape base
FROM node:24.18.0-bookworm-slim AS base
WORKDIR /app/backend
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY backend/package*.json ./
RUN npm ci

# Étape dev
FROM base AS dev
CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npm run start:dev"]

# Étape build
FROM base AS build
WORKDIR /app
COPY shared shared
COPY backend/ backend
WORKDIR /app/backend
RUN if [ -f .env.production ]; then \
        NODE_ENV=production npx prisma generate; \
    else \
        npx prisma generate; \
    fi
RUN npm run build

# Étape prod
FROM node:24.18.0-bookworm-slim AS prod
WORKDIR /app/backend
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=build /app/backend/dist ./dist
COPY backend/prisma ./prisma
COPY backend/src ./src
COPY backend/tsconfig*.json ./
COPY backend/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/backend/node_modules/.prisma ./node_modules/.prisma
COPY --from=build /app/backend/node_modules/@prisma ./node_modules/@prisma
CMD ["node", "dist/main"]
