# Étape de base commune
FROM node:20-alpine AS base
WORKDIR /app/frontend
#RUN mkdir frontend
COPY frontend/package*.json .
RUN npm install

# Étape de développement (hot reload)
FROM base AS dev
CMD ["npm", "run", "dev"]

# Étape de build (compilation en HTML/JS/CSS)
FROM base AS build
# COPY frontend .
RUN npm run build

# Étape de production (serveur nginx)
FROM nginx:alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
