# Étape de base commune
FROM node:20-alpine AS base
WORKDIR /app/frontend
#RUN mkdir frontend
COPY frontend/package*.json ./
RUN npm install

# Étape de développement (hot reload)
FROM base AS dev
CMD ["npm", "run", "dev"]

# Étape de build (compilation en HTML/JS/CSS)
FROM base AS build
WORKDIR /app
COPY shared/ shared
COPY backend backend
COPY frontend/ frontend
WORKDIR /app/backend
RUN npx prisma@6.10.1 generate --generator shared
WORKDIR /app/frontend
RUN npm run build

# Étape de production (serveur nginx)
FROM nginx:alpine AS prod
COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]