name: app

services:
  postgres:
    image: postgres:15
    restart: always
    # ports:
    #   - '5432:5432' # Mappe le port 5432 du conteneur au port 5433 de l'hôte VM
    env_file:
      - ../backend/.env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    # SECURITY TEST
    user: '999:999'
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
      - /var/run/postgresql:rw,noexec,nosuid
    cap_drop: [ALL]
    cap_add: [CHOWN, SETGID, SETUID]
    security_opt: [no-new-privileges:true]

  backend:
    build:
      context: .. # Le contexte est la racine du dépôt (/var/www/mon-app)
      dockerfile: docker/Dockerfile.backend # Chemin relatif depuis le contexte
      target: prod # Utilise l'étape 'prod' de Dockerfile.backend
    depends_on:
      - postgres
    env_file:
      - ../backend/.env.production
    restart: always

  frontend:
    build:
      context: .. # Le contexte est la racine du dépôt (/var/www/mon-app)
      dockerfile: docker/Dockerfile.frontend # Chemin relatif depuis le contexte
      target: prod # Utilise l'étape 'prod' de Dockerfile.frontend
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - backend

volumes:
  pgdata:
