worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;
  resolver 127.0.0.11 valid=30s; # Docker's built-in DNS resolver

  sendfile        on;
  keepalive_timeout  65;

  # upstream backend {
  #   server backend:3000;
  # }

  server {
    listen 80;
    server_name localhost;

    # Serveur frontend React
    root /usr/share/nginx/html;
    index index.html;

    location / {
      try_files $uri /index.html;
    }

    # Proxy des appels API vers le backend
    location /api/ {
      proxy_pass http://backend:3000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
